# names = []
# n1 = input("enter a name: ")
# names.append(n1)
# n1 = input("enter a name: ")
# names.append(n1)
# n1 = input("enter a name: ")
# names.append(n1)
# n1 = input("enter a name: ")
# names.append(n1)
# n1 = input("enter a name: ")
# names.append(n1)
# n1 = input("enter a name: ")
# names.append(n1)
# print(names)
# print(names[::2])
months = []
m = input("enter month number: ")
months.append(m)
m = input("enter month number: ")
months.append(m)
m = input("enter month number: ")
months.append(m)
m = input("enter month number: ")
months.append(m)
m = input("enter month number: ")
months.append(m)
m = input("enter month number: ")
months.append(m)
print(months)
if "7" in months:
    print("yeh...")